# Generated by Django 3.1.1 on 2020-09-14 17:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('nome_fantasia', models.CharField(blank=True, max_length=64, null=True)),
                ('cpf_cnpj', models.IntegerField(blank=True, null=True)),
                ('indicador_ie', models.CharField(choices=[('CONTRIB', 'Contribuinte ICMS'), ('ISENTO', 'Isento de cadastro'), ('NAO_CONTRIB', 'Não contribuinte')], max_length=18)),
                ('ie', models.IntegerField(blank=True, null=True)),
                ('nome_do_responsavel', models.CharField(blank=True, max_length=32, null=True)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', models.IntegerField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, max_length=128, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=32, null=True)),
                ('bairro', models.CharField(blank=True, max_length=32, null=True)),
                ('cidade', models.CharField(blank=True, max_length=32, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('pais', models.CharField(blank=True, max_length=32, null=True)),
                ('cliente', models.BooleanField(default=False)),
                ('fornecedor', models.BooleanField(default=False)),
                ('transportador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeDeMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('preco_compra', models.IntegerField(blank=True, null=True)),
                ('preco_venda', models.IntegerField(blank=True, null=True)),
                ('ean_gtin', models.IntegerField(blank=True, null=True)),
                ('ncm', models.IntegerField(blank=True, null=True)),
                ('produzido', models.BooleanField()),
                ('observacoes', models.CharField(blank=True, max_length=256, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.categoria')),
                ('unidade_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.unidadedemedida')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
