# Generated by Django 3.1.1 on 2020-09-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contato',
            name='fornecedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contato',
            name='transportador',
            field=models.BooleanField(default=False),
        ),
    ]
