# Generated by Django 3.1.1 on 2020-09-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_defaultmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultModel',
        ),
    ]
