# Generated by Django 3.1.1 on 2020-09-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_delete_defaultmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='observacoes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
